### PR TITLE
First attempt at English translation for the project

### LINKED ISSUE #118: Please add an English READ_ME, 不然老外看到会很困扰的
毕竟这里是github, 老外点进来都不知道啥东西

### PR DESCRIPTION
**Pull request by Rodeoclash**
Hopefully this helps resolve #118 

I've put this together by reading about the Putian investment group and the article listed in the PR then applying that to a Google translation of the article. I'm not sure that I've done everything correctly so feedback is welcome.

### CODE REVIEW

**Comment by chantisnake** [comment]
我觉得分成两个文件 readme 和 readme_eng 更好，不知道大家怎么看

**Comment by xokctah** [comment]
Agree with @chantisnake . It's better to be 2 separated files. @Rodeoclash would you mind create a new MD file and link to it from the current home page?

**Comment by Rodeoclash** [comment]
Yep!

**Comment by Rodeoclash** [comment]
@xokctah Any thoughts about where to put the link to the English translation? I've moved it to under the first paragraph.

**Comment by xokctah** [comment]
It looks all good to me. Thanks @Rodeoclash !

**Pull request merged**
